### ISSUE TITLE
The ribbon is blurry on HiDPI devices

### ISSUE THREAD

**Issue by hyperscalar** [theme-next/theme-next-canvas-ribbon#1]
# The Problem
The current version of this plugin performed poorly on high DPI devices, such as MacBook Pro with Retina Display. As shown below:
<img width="543" alt="blur" src="https://user-images.githubusercontent.com/23711687/47061502-57d3ca80-d204-11e8-827f-5b6f1a2b2b1c.png">
Notice those edges and angles, they are obviously less sharp than they should be.

# The Cause
As a result of my investigation, the source [canvas-ribbon](https://github.com/zproo/canvas-ribbon) of this plugin has some adaption problems on high DPI devices.

# A Solution
Although I'm not able to fix the source code directly, I found another solution for this. Use this [hustcc/ribbon.js](https://github.com/hustcc/ribbon.js) as the source of the plugin, instead of the buggy original one. By applying the new source, it fixes the problem effectively as shown below:
<img width="543" alt="sharp" src="https://user-images.githubusercontent.com/23711687/47064304-7f7d5f80-d211-11e8-85e5-274aca97fd63.png">
As you can see, this is way sharper than the original one.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/theme-next-canvas-ribbon/commit/2b41ae14433eb4a13cd99ac9736635723e813c32
